# Site settings
title: "执着的路-that-wang"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://the-wang.github.io" # the base hostname & protocol for your site
github_username: the-wang

timezone: Beijing
gems: ['jekyll-paginate']

# Build settings
highlighter: rouge
permalink: /:categories/:title/

markdown: kramdown
# markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

paginate: 25

theme: jekyll-theme-time-machine